services:

  react-lazy-dev:
    profiles:
      - dev
    image: node:22-alpine
    working_dir: /app
    ports:
      - "6080:80"
    volumes:
      - ./:/app
      - react-lazy-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 80"

  # $docker compose --profile prod up react-lazy-prod
  react-lazy-prod:
    profiles:
      - prod
    container_name: react-lazy-prod
    # image: httpd:2.4
    image: nginx:1.26-alpine
    ports:
      - "5080:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro

volumes:
  react-lazy-node-modules: